/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mvccalculator.View;

import javax.swing.JTextField;

public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bttn_primo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bttn_7 = new javax.swing.JButton();
        bttn_8 = new javax.swing.JButton();
        bttn_4 = new javax.swing.JButton();
        bttn_1 = new javax.swing.JButton();
        bttn_0 = new javax.swing.JButton();
        bttn_5 = new javax.swing.JButton();
        bttn_9 = new javax.swing.JButton();
        bttn_2 = new javax.swing.JButton();
        bttn_c = new javax.swing.JButton();
        bttn_6 = new javax.swing.JButton();
        bttn_3 = new javax.swing.JButton();
        bttn_float = new javax.swing.JButton();
        bttn_divide = new javax.swing.JButton();
        bttn_multiply = new javax.swing.JButton();
        bttn_substraction = new javax.swing.JButton();
        bttn_addition = new javax.swing.JButton();
        bttn_avg = new javax.swing.JButton();
        bttn_mplus = new javax.swing.JButton();
        bttn_equals = new javax.swing.JButton();
        bttn_bin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MVC Calculator");

        bttn_primo.setText("Prime");
        bttn_primo.setForeground(java.awt.Color.RED);

        jButton1.setText("Data");
        jButton1.setForeground(java.awt.Color.RED);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bttn_7.setText("7");
        bttn_7.setForeground(java.awt.Color.RED);

        bttn_8.setText("8");
        bttn_8.setForeground(java.awt.Color.RED);
        bttn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_8ActionPerformed(evt);
            }
        });

        bttn_4.setText("4");
        bttn_4.setForeground(java.awt.Color.RED);
        bttn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_4ActionPerformed(evt);
            }
        });

        bttn_1.setText("1");
        bttn_1.setForeground(java.awt.Color.RED);
        bttn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_1ActionPerformed(evt);
            }
        });

        bttn_0.setText("0");
        bttn_0.setForeground(java.awt.Color.RED);
        bttn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_0ActionPerformed(evt);
            }
        });

        bttn_5.setText("5");
        bttn_5.setForeground(java.awt.Color.RED);
        bttn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_5ActionPerformed(evt);
            }
        });

        bttn_9.setText("9");
        bttn_9.setForeground(java.awt.Color.RED);
        bttn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_9ActionPerformed(evt);
            }
        });

        bttn_2.setText("2");
        bttn_2.setForeground(java.awt.Color.RED);
        bttn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_2ActionPerformed(evt);
            }
        });

        bttn_c.setText("c");
        bttn_c.setForeground(java.awt.Color.RED);
        bttn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_cActionPerformed(evt);
            }
        });

        bttn_6.setText("6");
        bttn_6.setForeground(java.awt.Color.RED);
        bttn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_6ActionPerformed(evt);
            }
        });

        bttn_3.setText("3");
        bttn_3.setForeground(java.awt.Color.RED);
        bttn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_3ActionPerformed(evt);
            }
        });

        bttn_float.setText(".");
        bttn_float.setForeground(java.awt.Color.RED);
        bttn_float.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_floatActionPerformed(evt);
            }
        });

        bttn_divide.setText("/");
        bttn_divide.setForeground(java.awt.Color.RED);
        bttn_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_divideActionPerformed(evt);
            }
        });

        bttn_multiply.setText("*");
        bttn_multiply.setForeground(java.awt.Color.RED);
        bttn_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_multiplyActionPerformed(evt);
            }
        });

        bttn_substraction.setText("-");
        bttn_substraction.setForeground(java.awt.Color.RED);
        bttn_substraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_substractionActionPerformed(evt);
            }
        });

        bttn_addition.setText("+");
        bttn_addition.setForeground(java.awt.Color.RED);
        bttn_addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_additionActionPerformed(evt);
            }
        });

        bttn_avg.setText("avg");
        bttn_avg.setForeground(java.awt.Color.RED);
        bttn_avg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_avgActionPerformed(evt);
            }
        });

        bttn_mplus.setText("M+");
        bttn_mplus.setForeground(java.awt.Color.RED);
        bttn_mplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_mplusActionPerformed(evt);
            }
        });

        bttn_equals.setText("=");
        bttn_equals.setForeground(java.awt.Color.RED);
        bttn_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_equalsActionPerformed(evt);
            }
        });

        bttn_bin.setText("Binary");
        bttn_bin.setForeground(java.awt.Color.RED);
        bttn_bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_binActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2.setBackground(java.awt.Color.BLACK);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bttn_7)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_8)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_9))
                            .addComponent(bttn_primo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttn_bin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bttn_divide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttn_avg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bttn_1)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_2)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_3)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_substraction))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bttn_0)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_c)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_float)
                                .addGap(18, 18, 18)
                                .addComponent(bttn_addition)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttn_equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bttn_4)
                        .addGap(18, 18, 18)
                        .addComponent(bttn_5)
                        .addGap(18, 18, 18)
                        .addComponent(bttn_6)
                        .addGap(18, 18, 18)
                        .addComponent(bttn_multiply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttn_mplus, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bttn_bin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttn_primo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttn_9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttn_7)
                        .addComponent(bttn_8)
                        .addComponent(bttn_divide)
                        .addComponent(bttn_avg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_4)
                    .addComponent(bttn_5)
                    .addComponent(bttn_6)
                    .addComponent(bttn_multiply)
                    .addComponent(bttn_mplus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttn_1)
                            .addComponent(bttn_2)
                            .addComponent(bttn_3)
                            .addComponent(bttn_substraction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttn_0)
                            .addComponent(bttn_c)
                            .addComponent(bttn_float)
                            .addComponent(bttn_addition)))
                    .addComponent(bttn_equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_8ActionPerformed

    private void bttn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_4ActionPerformed

    private void bttn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_1ActionPerformed

    private void bttn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_0ActionPerformed

    private void bttn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_5ActionPerformed

    private void bttn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_9ActionPerformed

    private void bttn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_2ActionPerformed

    private void bttn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_cActionPerformed

    private void bttn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_6ActionPerformed

    private void bttn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_3ActionPerformed

    private void bttn_floatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_floatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_floatActionPerformed

    private void bttn_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_divideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_divideActionPerformed

    private void bttn_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_multiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_multiplyActionPerformed

    private void bttn_substractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_substractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_substractionActionPerformed

    private void bttn_additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_additionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_additionActionPerformed

    private void bttn_avgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_avgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_avgActionPerformed

    private void bttn_mplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_mplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_mplusActionPerformed

    private void bttn_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_equalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_equalsActionPerformed

    private void bttn_binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_binActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_binActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bttn_0;
    public javax.swing.JButton bttn_1;
    public javax.swing.JButton bttn_2;
    public javax.swing.JButton bttn_3;
    public javax.swing.JButton bttn_4;
    public javax.swing.JButton bttn_5;
    public javax.swing.JButton bttn_6;
    public javax.swing.JButton bttn_7;
    public javax.swing.JButton bttn_8;
    public javax.swing.JButton bttn_9;
    public javax.swing.JButton bttn_addition;
    public javax.swing.JButton bttn_avg;
    public javax.swing.JButton bttn_bin;
    public javax.swing.JButton bttn_c;
    public javax.swing.JButton bttn_divide;
    public javax.swing.JButton bttn_equals;
    public javax.swing.JButton bttn_float;
    public javax.swing.JButton bttn_mplus;
    public javax.swing.JButton bttn_multiply;
    public javax.swing.JButton bttn_primo;
    public javax.swing.JButton bttn_substraction;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
